version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/scripts/app.sh"]
    image: api-im
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO

      - SECRET=secret
      - HASH=hash
      - DB_NAME=default_db
      - DB_USER=gen_user
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=:&Y=0<^7t0=V,(

      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=gen_user
      - POSTGRES_PASSWORD=:&Y=0<^7t0=V,(
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:7 
    container_name: redis 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 


volumes:
  postgres_data:
  redis_data:  